name: Docker Image CI

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Java JDK
        uses: actions/setup-java@v1.4.4
        with:
          java-version: 19
          
      - name: Setup Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.9.2
      
      - name: Build JAR
        run: mvn clean package
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Deploy with Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d
      
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile_postgres
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/restaurant:latest
        
        
        
